server:
  port: 8082
spring:
  application:
    name: jooq-demo
  datasource:
    driver-class-name: @db.driver@
    url: @db.url@
    username: @db.username@
    password: @db.password@
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    sql-migration-prefix: v
  jooq:
    sql-dialect: postgres

